# Generated by Django 5.0.1 on 2024-01-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beeyard',
            old_name='beekeper',
            new_name='beekeeper',
        ),
        migrations.AlterField(
            model_name='hive',
            name='beeyard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='hive.beeyard'),
        ),
    ]
