# Generated by Django 5.0.1 on 2024-01-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0002_rename_beekeper_beeyard_beekeeper_alter_hive_beeyard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contamination',
            name='date',
            field=models.DateField(auto_now=True, help_text='Date the contamination was found'),
        ),
        migrations.AddField(
            model_name='contamination',
            name='hive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contaminations', to='hive.hive'),
            preserve_default=False,
        ),
    ]
