# Generated by Django 5.0.1 on 2024-01-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_contamination_date_contamination_hive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hive',
            old_name='age_queen',
            new_name='queen_year',
        ),
    ]
