# Generated by Django 5.0.1 on 2024-01-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hive', '0004_rename_age_queen_hive_queen_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'hive'), ('model', 'quantity')), models.Q(('app_label', 'hive'), ('model', 'artificialswarming')), models.Q(('app_label', 'hive'), ('model', 'treatment')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='hive_affected',
            field=models.ForeignKey(help_text='The Hive concerned by the intervention', on_delete=django.db.models.deletion.CASCADE, to='hive.hive'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
