# Generated by Django 5.0.1 on 2024-01-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeyard',
            name='name',
            field=models.CharField(default='Buddyville', help_text='A Name to Identify the Bee Yard Easily', max_length=100),
            preserve_default=False,
        ),
    ]
