# Generated by Django 5.0.1 on 2024-01-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0002_beeyard_name'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'apiary'), ('model', 'quantity')), models.Q(('app_label', 'apiary'), ('model', 'hive')), models.Q(('app_label', 'apiary'), ('model', 'treatment')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='ArtificialSwarming',
        ),
    ]
