# Generated by Django 5.0.1 on 2024-01-05 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0004_alter_hive_options_alter_intervention_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeyard',
            name='beekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeyards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Beekeeper',
        ),
    ]
