# Generated by Django 5.0.1 on 2024-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0005_alter_beeyard_beekeeper_delete_beekeeper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Quantity', 'verbose_name_plural': 'Quanitities'},
        ),
        migrations.AddField(
            model_name='hive',
            name='species',
            field=models.CharField(choices=[('Black bee', 'Black bee'), ('Italian bee', 'Italian bee'), ('Caucasian bee', 'Caucasian bee'), ('Carnolian bee', 'Carnolian bee'), ('Buckfast bee', 'Buckfast bee')], default='Black bee', help_text='Type of bees'),
            preserve_default=False,
        ),
    ]
