# Generated by Django 5.0.1 on 2024-01-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0006_alter_quantity_options_hive_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeyard',
            name='beekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beeyards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hive',
            name='beeyard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hives', to='apiary.beeyard'),
        ),
    ]
