# Generated by Django 5.0.1 on 2024-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0007_alter_beeyard_beekeeper_alter_hive_beeyard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(choices=[('Artificial Swarming', 'Artificial Swarming'), ('Destruction Queen Cells', 'Destruction Queen Cells'), ('Harvest', 'Harvest'), ('Health Check', 'Health Check'), ('Super Installation', 'Super Installation'), ('Syrup Distribution', 'Syrup Distribution'), ('Treatment', 'Treatment')], help_text='The type of intervention from the given list'),
        ),
    ]
