# Generated by Django 5.0.1 on 2024-01-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0009_harvest_syrupdistribution_delete_quantity'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='For an Artificial Swarming select Apiary | Hive to select the parent hive. \n        For a treatment, select Apiary | treatment to select the type of treatment. \n        Quantity and treatment objects must be created before they can be selected for an intervention.', limit_choices_to=models.Q(models.Q(('app_label', 'apiary'), ('model', 'harvest')), models.Q(('app_label', 'apiary'), ('model', 'hive')), models.Q(('app_label', 'apiary'), ('model', 'syrupdistribution')), models.Q(('app_label', 'apiary'), ('model', 'treatment')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
