# Generated by Django 5.0.1 on 2024-01-08 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0011_alter_hive_queen_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_beekeeper_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allows_public_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
