# Generated by Django 5.0.1 on 2024-01-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0012_publiccontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicContact',
        ),
    ]
