# Generated by Django 5.0.1 on 2024-01-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0013_delete_publiccontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='name',
            field=models.CharField(default='HiveName', help_text='A Name to Identify the Hive Easily', max_length=100),
            preserve_default=False,
        ),
    ]
