# Generated by Django 5.0.1 on 2024-01-11 21:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0015_alter_hive_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeyard',
            name='beekeeper',
            field=models.ForeignKey(help_text='The owner of the beeyard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beeyards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contamination',
            name='hive',
            field=models.ForeignKey(help_text='The infected hive.', on_delete=django.db.models.deletion.CASCADE, related_name='contaminations', to='apiary.hive'),
        ),
        migrations.AlterField(
            model_name='contamination',
            name='type',
            field=models.CharField(choices=[('parasite', 'Parasite'), ('illness', 'Illness')], help_text='The type of contamination affecting the hive'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='beeyard',
            field=models.ForeignKey(help_text='The beeyard where the hive is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hives', to='apiary.beeyard'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='queen_year',
            field=models.IntegerField(default=2024, help_text='The year the queen bee was born.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(choices=[('artificial_swarming', 'Artificial Swarming'), ('destruction_queen_cells', 'Destruction Queen Cells'), ('harvest', 'Harvest'), ('health_check', 'Health Check'), ('super_installation', 'Super Installation'), ('syrup_distribution', 'Syrup Distribution'), ('treatment', 'Treatment')], help_text='The type of intervention from the given list'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='The ID of the FK object needed to complete the intervention information..', null=True),
        ),
        migrations.AlterField(
            model_name='syrupdistribution',
            name='syrup_type',
            field=models.CharField(choices=[('nectar', 'nectar'), ('cane_sugar', 'cane_sugar'), ('white_sugar', 'white_sugar'), ('raw_sugar', 'raw_sugar')], help_text='The type of syrup provided to the hive'),
        ),
    ]
