# Generated by Django 5.0.1 on 2024-01-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0017_alter_treatment_treatment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('antifungal', 'Antifungal'), ('apivar', 'Apivar'), ('oxalic_acid', 'Oxalic Acid')], help_text='Name of the treatment applied to the hive', unique=True),
        ),
    ]
